# Copyright 2022-present The ZTDBP Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ConfigMap
apiVersion: v1
metadata:
  name: zaportal-nginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  10240;
    }

    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;

      keepalive_timeout 65;

      access_log off;
      error_log off;

      include mime.types;
      default_type application/octet-stream;

      gzip  on;
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_types text/html text/richtext text/plain text/css text/x-script text/x-component text/x-java-source text/x-markdown application/javascript application/x-javascript text/javascript text/js image/x-icon image/vnd.microsoft.icon application/x-perl application/x-httpd-cgi text/xml application/xml application/xml+rss application/vnd.api+json  application/x-protobuf  application/json multipart/bag multipart/mixed application/xhtml+xml font/ttf font/otf font/x-woff image/svg+xml application/vnd.ms-fontobject application/ttf application/x-ttf application/otf application/x-otf application/truetype application/opentype application/x-opentype application/font-woff application/eot application/font application/font-sfnt application/wasm application/javascript-binast  application/manifest+json  application/ld+json;

      brotli on;
      brotli_static on;
      brotli_comp_level 6;
      brotli_types text/html text/richtext text/plain text/css text/x-script text/x-component text/x-java-source text/x-markdown application/javascript application/x-javascript text/javascript text/js image/x-icon image/vnd.microsoft.icon application/x-perl application/x-httpd-cgi text/xml application/xml application/xml+rss application/vnd.api+json  application/x-protobuf  application/json multipart/bag multipart/mixed application/xhtml+xml font/ttf font/otf font/x-woff image/svg+xml application/vnd.ms-fontobject application/ttf application/x-ttf application/otf application/x-otf application/truetype application/opentype application/x-opentype application/font-woff application/eot application/font application/font-sfnt application/wasm application/javascript-binast  application/manifest+json  application/ld+json;

      server {
          listen 80 default_server;

          server_name _;

          root /usr/share/nginx/html;
          index index.html;

          location ^~ /api/ {
             proxy_pass   http://127.0.0.1:8080;
          }

          location ^~ /a/ {
             proxy_pass   http://127.0.0.1:8080;
          }

          location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
            expires 30d;
            access_log off;
          }

          location ~ .*\.(js|css)?$ {
            expires 7d;
            access_log off;
          }

          location / {
            try_files $uri $uri/ /index.html;
          }
      }
    }
