# Copyright 2022-present The ZTDBP Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#APP ENV
app:
  env: "release" # dev,release
  sysname: "ZAManager"
  port: 8080
  domain: DOMAIN

#Mysql
mysql:
  dbname: "zta"
  prefix: "zta_"
  pool:
    pool-min-cap: 10
    pool-ex-cap: 5
    pool-max-cap: 40
    pool-idle-timeout: 3600
    pool-wait-count: 1000
    pool-wai-timeout: 30
  write:
    host: "ZTA_MYSQL_HOST"
    port: 3306
    user: "ZTA_MYSQL_USER"
    password: "ZTA_MYSQL_PASSWORD"

#Redis
redis:
  addr: "ZTA_REDIS_ADDR"

#CA
ca:
  base-url: "ZTA_CA_BASE_URL"
  sign-url: "ZTA_CA_SIGN_URL"
  ocsp-url: "ZTA_CA_OCSP_URL"
  version: "/api/v1"
  auth-key: "ZTA_CA_AUTH_KEY"
